theme: minima
title: Twinkal's Blogs
author: Twinkal Barai
email: twinkal.barai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brag Sheet:
  FBLA member,
  EB Writers Coalition,
  EB UNICEF member,
  Tutor

# social links
twitter_username: t_wklb
github_username:  t3win

show_excerpts: true # set to false to remove excerpts on the homepage
