theme: minima
title: Twinkal's Blogs
author: Twinkal Barai
email: twinkal.barai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! My name is Twinkal and I am passionate about biology, especially molecular biology.

# social links
twitter_username: t_wklb
github_username:  t3win

show_excerpts: true # set to false to remove excerpts on the homepage
